#!/bin/sh
set -e

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p supervisor 
fi

# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/supervisor" ] || [ -e "/etc/init/supervisor.conf" ]; then
	if [ ! -e "/etc/init/supervisor.conf" ]; then
		update-rc.d supervisor defaults >/dev/null
	fi
	invoke-rc.d supervisor start || exit $?
fi
# End automatically added section
